version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: snmp-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: snmpdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: snmp-rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7
    container_name: snmp-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

volumes:
  postgres-data: