<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SNMP.WORKER_SERVICE-50497b91-ea2e-477a-bda3-abd2e7444235</UserSecretsId>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lextm.SharpSnmpLib" Version="12.5.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SNMP.BLL\Snmp.Business.csproj" />
    <ProjectReference Include="..\SNMP.ENTITY\Snmp.Entity.csproj" />
    <ProjectReference Include="..\Snmp.Infrastructure\Snmp.Infrastructure.csproj" />
  </ItemGroup>
</Project>
